#!/bin/bash

echo "This script will delete ISAM openldap, postgresql, and isamconfig deployments on the target Docker EE 2.0 System.  Do you want to continue? Y,N"
read RESPONSE

case $RESPONSE in 
   [yY]* ) echo "+++Deleting deployments..."
           kubectl delete deployments openldap postgresql isamconfig
           echo "+++Deleting services..."
           kubectl delete services openldap postgresql isamconfig
           echo "+++Deleting secrets..."
           kubectl delete secrets openldap-keys postgresql-keys dockerlogin configreader
           sleep 10
           kubectl get pods
           exit;;
   [nN]* ) echo "No action.  Exiting"
           exit;;
   * )     echo "Y or N, please"
esac
