#!/bin/bash
echo This script performs the orchestration of IBM Security Access Manager on Docker Enterprise Edition 2.0. See https://www.ibm.com/blogs/sweeden/running-isam-ibm-cloud/ for detailed description of each step. Do you want to continue? Y,n

read RESPONSE

case $RESPONSE in 
   [yY]* ) echo +++ Create key and certificate files for OpenLDAP...
           openssl req -x509 -newkey rsa:4096 -keyout "ldap.key" -out "ldap.crt" -days 365 -subj "/C=US/ST=CA/L=SanFrancisco/O=Docker/CN=OpenLDAP" -nodes
           cp ldap.crt ca.crt
           echo +++ Create a Diffie-Hellman parameter file for OpenLdap
           openssl dhparam -out "dhparam.pem" 2048
           echo +++ Create a Kubernetes Secret for Ldap
           kubectl create secret generic openldap-keys --from-file "ldap.crt" --from-file "ldap.key" --from-file "ca.crt" --from-file "dhparam.pem"
           echo +++ Create the K8s Deployment and Service
           kubectl create -f openldap.yaml
           kubectl get pods
           kubectl get svc openldap
           echo 
           echo +++ Deploying Postgresql
           echo +++ Create key and certificate files for Postgresql
           openssl req -x509 -newkey rsa:4096 -keyout "postgres.key" -out "postgres.crt" -days 365 -subj "/C=US/ST=CA/L=SFO/O=Docker/CN=Postgresql" -nodes
           cat postgres.key postgres.crt > server.crt
           echo +++ Create Kubernetes Postgres secret
           kubectl create secret generic postgresql-keys --from-file "server.crt"
           echo +++ Create Postgresql Deployment and Service
           kubectl create -f postgresql.yaml
           echo
           kubectl get pods
           kubectl get svc postgresql
           echo +++ Create ISAM Config Deployment and Service
           kubectl create -f isamconfig.yaml
           kubectl get pods
           echo DONE!!!
           exit;;         
   [nN]* ) echo "No action.  Exiting"
           exit;;
   * )     echo "Y or N, please"
esac







